// <auto-generated />
using Authix.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Authix.Data.Migrations
{
    [DbContext(typeof(AuthixDbContext))]
    [Migration("20250412105856_InitUsers")]
    partial class InitUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.15");

            modelBuilder.Entity("Authix.Auth.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "$2a$11$Lro27MtCVaQ4qKU72YZ7CO0gGDUoL4fpHWh46t02r1HTWrXNLWaJO",
                            Role = 2,
                            Username = "Squee"
                        },
                        new
                        {
                            Id = 2,
                            PasswordHash = "$2a$11$qK1dnONJri1jf8sEt4jmF.hjEcwFb15N5Kl9bOYTVU/9PIR4pHJ/S",
                            Role = 2,
                            Username = "Owla"
                        },
                        new
                        {
                            Id = 3,
                            PasswordHash = "$2a$11$S6eqlMpjIR8Ty4/NsBpBre3UBdM3jGnvZ7thLgXAk/49LJKT/CZMK",
                            Role = 1,
                            Username = "Casha"
                        },
                        new
                        {
                            Id = 4,
                            PasswordHash = "$2a$11$rkn2/K.VVSEcA/3O5tgaWe8gp2D0xJFBYRdfa6fPZaXEfYKO6X.tO",
                            Role = 2,
                            Username = "Tweetle"
                        },
                        new
                        {
                            Id = 5,
                            PasswordHash = "$2a$11$YznPs0g7MbYYq0zvEflOAeIls7LaxIZ8ptLG8nwMDpNrIltXK2xlC",
                            Role = 1,
                            Username = "Grizzle"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
